version: '3.5'

services:
  postgresql_db:
    container_name: optimization_db_postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
  redis_db:
    container_name: optimization_db_redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_password
      - REDIS_PORT=6379
    image: redis:7.2.4-alpine
